aws_fargate/gateway/apps/fossa_gateway/app.py
"""
Demo to run flask with local debugging or with gunicorn.
"""
from flask import Flask

from views import web_views


def create_app(settings_class):
    """
    Create a Flask app that can be run as a server

    @param settings_class: (str) or Config class
        to settings. See Flask docs.

    @return: Flask
        The flask app
    """
    app = Flask(__name__)
    app.config.from_object(settings_class)
    app.register_blueprint(web_views, url_prefix="/")

    return app


def run_local_app():
    """
    Run app locally just for development, don't use this in production, see main.py.
    """
    settings = "config.LocalConfig"
    app = create_app(settings)

    app.run(
        debug=app.config["DEBUG"],
        host="0.0.0.0",
        port=app.config["HTTP_PORT"],
    )


if __name__ == "__main__":
    run_local_app()

aws_fargate/gateway/apps/fossa_gateway/controllers.py
"""
Created on 17 Mar 2024

@author: si
"""
import boto3
import requests

# TODO - get AWS region from config
ecs = boto3.client("ecs", region_name="eu-west-2")


def cluster_arns():
    """
    @return: list of str - the ARNs of available clusters
    """
    r = ecs.list_clusters()
    return r["clusterArns"]


def task_summary(cluster_arn):
    """
    Some details about running tasks in a cluster.

    @param cluster_arn: (str)
    @return list of dict. All taken from AWS/boto3 api. If key not present, None is returned.
        with keys-
        - startedAt
        - lastStatus
        - group
        - ipv4_private
        - task_id
    """
    if cluster_arn not in cluster_arns():
        raise ValueError("Unknown cluster arn")

    tasks = ecs.list_tasks(cluster=cluster_arn)

    if "taskArns" not in tasks or len(tasks["taskArns"]) == 0:
        return []

    describe_tasks = ecs.describe_tasks(
        cluster=cluster_arn,
        tasks=tasks["taskArns"],
    )

    copy_fields = ["startedAt", "lastStatus", "group"]
    ts = []
    for task_details in describe_tasks["tasks"]:
        summary = {f: task_details.get(f) for f in copy_fields}

        summary["ipv4_private"] = None
        if len(task_details["containers"]) > 0:
            network_interfaces = task_details["containers"][0].get("networkInterfaces", [])
            if len(network_interfaces) > 0:
                summary["ipv4_private"] = network_interfaces[0].get("privateIpv4Address")

        if "taskArn" in task_details:
            arn_parts = task_details["taskArn"].split("/")
            if len(arn_parts) > 0:
                summary["task_id"] = arn_parts[-1]

        ts.append(summary)

    return ts


def fossa_node_info(fossa_node_port, cluster_arn, fossa_node_ipv4):
    """
    Query a Fossa worker node.

    This function is only needed in an environment where the nodes aren't reachable from the client
    using the gateway. e.g. private fossa nodes with a publically accessable gateway.

    @param cluster_arn: (str)
    @param fossa_node_ipv4: (str)
    @return: dict - see Fossa project :func:`fossa.views.api.node_info`
    """

    valid_ipv4 = [ts["ipv4_private"] for ts in task_summary(cluster_arn)]
    if fossa_node_ipv4 not in valid_ipv4:
        known_nodes = ",".join(valid_ipv4)
        raise ValueError(f"Unknown task: {fossa_node_ipv4} isn't in {known_nodes}")

    fossa_node_info_url = f"http://{fossa_node_ipv4}:{fossa_node_port}/api/0.01/node_info"
    r = requests.get(fossa_node_info_url)

    if r.status_code != 200:
        msg = (
            f"The Fossa node request returned http_status={r.status_code} for "
            f"url={fossa_node_info_url}"
        )
        raise ValueError(msg)

    return r.json()

aws_fargate/gateway/apps/fossa_gateway/main.py
"""
Run Flask app with gunicorn.

e.g.

$ DEPLOYMENT_ENVIRONMENT=Local python main.py
"""

import os

import gunicorn.app.base

from app import create_app


class StandaloneApplication(gunicorn.app.base.BaseApplication):
    """
    Run a WSGI web-app using gunicorn.
    """

    def __init__(self, app, options=None):
        self.options = options or {}
        self.application = app
        super().__init__()

    def load_config(self):
        config = {
            key: value
            for key, value in self.options.items()
            if key in self.cfg.settings and value is not None
        }
        for key, value in config.items():
            self.cfg.set(key.lower(), value)

    def load(self):
        return self.application


def run_fossa(deployment_config):
    """
    Run Fossa through gunicorn.

    @param deployment_config: (str or class or anything accepted by Flask's `app.config.from_object`)
        Used to choose the settings file. i.e. 'prod' uses .....settings.prod_config.Config
    """
    app = create_app(deployment_config)

    options = {
        "bind": "%s:%s" % ("0.0.0.0", app.config["HTTP_PORT"]),
        "workers": 4,
        "syslog": True,
        "timeout": 80,
    }

    StandaloneApplication(app, options).run()


if __name__ == "__main__":
    deployment_label = os.environ["DEPLOYMENT_ENVIRONMENT"]
    config_package = f"config.{deployment_label}Config"
    run_fossa(config_package)

aws_fargate/gateway/apps/fossa_gateway/views.py
"""
Non-API views in HTML
"""
from functools import wraps
from urllib.parse import quote_plus, unquote_plus

from flask import Blueprint, current_app, render_template, request

from controllers import cluster_arns, fossa_node_info, task_summary

web_views = Blueprint("web", __name__)


# TODO - login check for all of blueprint - @web_views.before_request


def check_auth(username, password):
    "Check basic auth."
    return username == "fossa" and password == current_app.config.get("HTTP_USER_PASSWORD")


def login_required(f):
    @wraps(f)
    def wrapped_view(**kwargs):
        auth = request.authorization
        if not (auth and check_auth(auth.username, auth.password)):
            return ("Unauthorized", 401, {"WWW-Authenticate": 'Basic realm="Login Required"'})

        return f(**kwargs)

    return wrapped_view


@web_views.route("/")
@login_required
def available_clusters():
    cluster_details = [{"url_encoded": quote_plus(c), "arn": c} for c in cluster_arns()]

    page_vars = {
        "cluster_arns": cluster_details,
    }
    return render_template("clusters.html", **page_vars)


@web_views.route("/<cluster_arn_encoded>/tasks")
@login_required
def tasks(cluster_arn_encoded):
    cluster_arn = unquote_plus(cluster_arn_encoded)

    page_vars = {
        "cluster_arn": cluster_arn,
        "cluster_arn_encoded": cluster_arn_encoded,
        "task_summary": task_summary(cluster_arn),
    }
    return render_template("tasks.html", **page_vars)


@web_views.route("/<cluster_arn_encoded>/node_info/<ipv4>")
@login_required
def node_info(cluster_arn_encoded, ipv4):
    """
    Fetch node info from the Fossa API in the cluster task running at `ipv4`.

    @param ipv4: (str)
    """
    cluster_arn = unquote_plus(cluster_arn_encoded)
    fossa_node_port = current_app.config["FOSSA_NODE_PORT"]
    node_info = fossa_node_info(fossa_node_port, cluster_arn, ipv4)

    print(node_info)

    page_vars = {
        "cluster_arn": cluster_arn,
        "ipv4": ipv4,
        **node_info,
    }
    return render_template("node_info.html", **page_vars)

aws_fargate/gateway/apps/fossa_gateway/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Fossa Gateway</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
	<main class="flex-shrink-0">
	  <div class="container">
	
	{% block body_content %}{% endblock %}  
	</div>
	</main>
	
	<footer class="footer mt-auto py-3 bg-light">
	  <div class="container">
	    <span class="text-muted">Fossa from <a href="https://github.com/Aye-Aye-Dev">Aye-Aye-dev</a> &copy; 2024</span>
	  </div>
	</footer>

    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> -->
  </body>
</html>

aws_fargate/gateway/apps/fossa_gateway/templates/clusters.html
{% extends "base.html" %}
{% block body_content %}

<h1>Available clusters</h1>

<ul>
{%for c in cluster_arns%}
<li><a href="{{ url_for('web.tasks', cluster_arn_encoded=c['url_encoded']) }}">{{c['arn']}}</a></li>
{%endfor%}
</ul>

{% endblock %}

aws_fargate/gateway/apps/fossa_gateway/templates/node_info.html
{% extends "base.html" %}
{% block body_content %}

<h1>Fossa node info from {{ipv4}} in {{cluster_arn}}</h1>


<h2>Node info</h2>

<table class="table table-striped">
  <tbody>
  {%for key,value in node_info.items()%}
    <tr>
      <th>{{key}}</th>
      <td>{{value}}</td>
    </tr>
  {%endfor%}
  </tbody>
</table>


<h2>Recently Completed Tasks</h2>
{%if recent_completed_tasks %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Model class</th>
      <th scope="col">Method</th>
      <th scope="col">Method kwargs</th>
      <th scope="col">Resolver context</th>
      <th scope="col">Started</th>
      <th scope="col">Finished</th>
      <th scope="col">Results</th>
    </tr>
  </thead>
  <tbody>
  {%for t in recent_completed_tasks%}
    <tr>
      <td>{{t.model_class}}</td>
      <td>{{t.method}}</td>
      <td>{{t.method_kwargs}}</td>
      <td>{{t.resolver_context}}</td>
      <td>{{t.started}}</td>
      <td>{{t.finished}}</td>
      <td>{{t.results}}</td>
    </tr>
  {%endfor%}
  </tbody>
</table>
{%else%}
<p>This Fossa node hasn't run any tasks since it started.</p>
{%endif%}

{% endblock %}

aws_fargate/gateway/apps/fossa_gateway/templates/tasks.html
{% extends "base.html" %}
{% block body_content %}

<h1>Tasks in {{cluster_arn}}</h1>

{%if task_summary %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Started</th>
      <th scope="col">Group</th>
      <th scope="col">Status</th>
      <th scope="col">Task Id</th>
      <th scope="col">Private IPv4</th>
    </tr>
  </thead>
  <tbody>
  {%for t in task_summary %}
    <tr>
      <td>{{t.startedAt}}</td>
      <td>{{t.group}}</td>
      <td>{{t.lastStatus}}</td>
      <td>{{t.task_id}}</td>
      <td>{% if t.group.startswith('service:fossa') %}
      		<a href="{{ url_for('web.node_info', ipv4=t.ipv4_private, cluster_arn_encoded=cluster_arn_encoded) }}">{{t.ipv4_private}}</a>
      	  {% else %}
      	  	{{t.ipv4_private}}
      	  {% endif %}
      </td>
    </tr>
  {%endfor%}
  </tbody>
</table>
{%else%}
<p>There are no tasks in the cluster.</p>
{%endif%}




{% endblock %}